BEGIN TRANSACTION;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494596042/linus-bike-mixte-8-lifestyle2-2000x931_wlkmbi.jpg', product_id = 12 WHERE id = 48;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401206/dutchi_lafnss.jpg', product_id = 2 WHERE id = 2;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401208/pronto_gte6sf.jpg', product_id = 1 WHERE id = 1;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494593599/linus-bike-scout-1-lifestyle1-2000x931_ehoqow.jpg', product_id = 8 WHERE id = 49;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494595762/linus-bike-dutchi-8-lifestyle1-2000x931_dnzyzt.jpg', product_id = 2 WHERE id = 38;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401206/gaston_ufppb6.jpg', product_id = 4 WHERE id = 4;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401207/libertine_j8zpau.jpg', product_id = 5 WHERE id = 5;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401205/avanti_apcwzp.jpg', product_id = 3 WHERE id = 3;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401206/brooks_flyer_kbihus.jpg', product_id = 12 WHERE id = 12;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401208/roadster_e36mmp.jpg', product_id = 6 WHERE id = 6;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401206/brooks_b67_jihmiy.jpg', product_id = 11 WHERE id = 11;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401207/nutcase_dots_hsqxm8.jpg', product_id = 10 WHERE id = 10;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401211/thousand_t8ulyv.jpg', product_id = 9 WHERE id = 9;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401207/mixte_b7rhtt.jpg', product_id = 7 WHERE id = 7;
UPDATE public.product_image SET name = 'main', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494401209/scout_iga5wq.jpg', product_id = 8 WHERE id = 8;
UPDATE public.product_image SET name = 'longpic', image = 'nutcase_dots_icon.jpg', product_id = 10 WHERE id = 46;
UPDATE public.product_image SET name = 'longpic', image = 'thousand_icon.jpg', product_id = 9 WHERE id = 45;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494596047/linus-bike-mixte-8-lifestyle3-2000x931_jikbsi.jpg', product_id = 7 WHERE id = 43;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494595926/linus-bike-gaston-3-lifestyle1-2000x931_nkbiow.jpg', product_id = 4 WHERE id = 40;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494596042/linus-bike-mixte-8-lifestyle2-2000x931_wlkmbi.jpg', product_id = 1 WHERE id = 37;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494598679/linus-bike-roadster-sport-lifestyle2-2000x931_qpk3tm.jpg', product_id = 6 WHERE id = 42;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494596054/linus-bike-mixte-8-lifestyle1-2000x931_vkvy3f.jpg', product_id = 5 WHERE id = 41;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494595820/linus-bike-avanti-2-lifestyle1-2000x931_21534031-8c46-4e16-bf37-aa30bfe59d03_q9fgsp.jpg', product_id = 3 WHERE id = 39;
UPDATE public.product_image SET name = 'longpic', image = 'http://res.cloudinary.com/alexpench/image/upload/v1494595933/linus-bike-gaston-3-lifestyle2-2000x931_m8q2kl.jpg', product_id = 11 WHERE id = 47;
commit;
end TRANSACTION;